### ISSUE TITLE
[QUESTION] why do we need to store the signatures in the repo?

### ISSUE THREAD

**Issue by sumanth-lingappa** [contributor-assistant/github-action#151] opened 2024-04-16 09:53 UTC
continuing #150 

there is a `path-to-signatures` attribute to this action, which stores the signature details of the contributor.

**Why do we need to store the signature details in our repo?** 

My branch is protected and this workflow keeps failing.

**Comment by ibakshay** [comment] 2024-04-27 20:06
closing as this issue is duplicate of https://github.com/contributor-assistant/github-action/issues/150

**Closed by ibakshay** 2024-04-27 20:06 UTC
Labels: bug

**Comment by sumanth-lingappa** [comment] 2024-04-28 02:29
I need to understand why do we need to store the CLA signatures in the repo?
